on: 
    repository_dispatch:
        types: ffmpeg_prod
    workflow_dispatch:
        inputs:
          m3u8_url:
            description: ''
            required: true
            type: string
          livestream_token:
            description: ''
            required: true
            type: string

name: Azure Container ARM Deployment Prod
  
jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:

        # Checkout code
      - uses: actions/checkout@main

        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_PROD }}

        # Deploy ARM template
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_PROD }}
          resourceGroupName: ${{ secrets.AZURE_RG_PROD }}
          template: ./arm-templates/azure_container_arm.json
          parameters: containerGroups_name=${{inputs.livestream_token}} m3u8_url=${{inputs.m3u8_url}} livepeer_key=${{inputs.livestream_token}}
        # output containerName variable from template
      - run: echo ${{ steps.deploy.outputs }}
