
# File: .github/workflows/workflowForFile.yml

on:
  workflow_dispatch:
    inputs:
      m3u8_url:
        description: ''
        required: true
        type: string
      livestream_token:
        description: ''
        required: true
        type: string

name: AzureCLISampleForFile

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Checkout
      uses: actions/checkout@v1

    - name: Azure CLI script file
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az account show
          az container exec --resource-group rg-livestream-dev --name ffmpeglivestream --exec-command "ffmpeg -fflags -igndts -hide_banner -i ${{ inputs.m3u8_url }} -bsf:a aac_adtstoasc -c copy -f flv rtmp://rtmp.livepeer.com/live/${{ inputs.livestream_token }}"
