
# File: .github/workflows/workflowForFile.yml

on:
  workflow_dispatch:
    inputs:
      m3u8_url:
        description: ''
        required: true
        type: string
      livestream_token:
        description: ''
        required: true
        type: string
      app_id:
        description: ''
        required: true
        type: string
      app_secret:
        description: ''
        required: true
        type: string
      tenant_id:
        description: ''
        required: true
        type: string


name: AzureCLISampleForFile

jobs:

  build-and-deploy:
    runs-on: self-hosted
    steps:

    - name: Run Azure CLi
      run : | 
        cd C:\\actions-runner
        az login --service-principal -u ${{inputs.app_id}} -p ${{inputs.app_secret}} --tenant ${{inputs.tenant_id}}
        az container exec --resource-group rg-livestream-dev --name ffmpeglivestream --exec-command "ffmpeg -fflags +igndts -hide_banner -i ${{inputs.m3u8_url}} -bsf:a aac_adtstoasc -c copy -f flv rtmp://rtmp.livepeer.com/live/${{inputs.livestream_token}}" --debug
  
