
# File: .github/workflows/workflowForFile.yml

on:
  workflow_dispatch:
    inputs:
      m3u8_url:
        description: ''
        required: true
        type: string
      livestream_token:
        description: ''
        required: true
        type: string
      app_id:
        description: ''
        required: true
        type: string
      app_secret:
        description: ''
        required: true
        type: string
      tenant_id:
        description: ''
        required: true
        type: string


name: AzureCLISampleForFile

jobs:

  build-and-deploy:
    runs-on: self-hosted
    steps:

    - name: Run Azure CLi
      run : | 
          az login --service-principal -u c6d56208-b87e-47bc-8020-142ff0485663 -p nVI8Q~Xf87gpJ58Qbm-HD09qIVjjGwwpgm6bGbo2 --tenant b8fcd764-567f-440d-8c7a-6218dac96c10
          az container exec --resource-group rg-livestream-dev --name ffmpeglivestream --exec-command "ffmpeg -fflags -igndts -hide_banner -i https://video-weaver.atl01.hls.ttvnw.net/v1/playlist/CqkEn12jm8MHAAuYrcADrf7MZnZ3iUMrxhe8-cPIHw-LA3kEWEeo2E5Ls9fSl7ovUrjKE2mzbtKFjbF8lGmT122ic4KTmmRgm6AF3Xj_-qEjNp_fb-g-RW7wa5qO8j8F_JBXoW3HdDi-SLLg4pdV_Ef8eJiOPn5OJslkvo8hWT9yHVS0XVKPxW02P4ZsKuu38tEwTSQCKSn-sSQcCqmY5ARyTmCu1kJ9AtaQ0FvgmNlj8FDWDNCjwFRV4B2zHFDLsNRQia1-NUN7QApt8yRg801mB_Z-hXhUY4yXM9YC8bsbkguRnPioWscUmj09SiZpOBRHKWA-FH0N1KevRRRysZgkvgXWm3xqKTOJZWe7Y6GV5jw2QbZQkK8GTMYe8zWJaFiZAK4KDMPIXgXJnxsdV6yMbI23KTCsu2nAx2eQam_Z0ZicEjolHQ0cyAZcJx9sz1UkFaWesRi825K5cAqk2u-MOlPGoAdG_ICU5sv3SNKrTrnqrPz-XiVvjkWY7AXNgsyDz8ZB9S6TMURnWRcWdvlC0lh0Z1_jLRufWN1S-NnmxBtZA81CJhTNJ7GjG8TxlNAnbV30IKI4Mr6729I1RYgF6ETEqUCa37cN5OVijhXqLKl3FMtHfGXi3V8kmIy1kVWdqP9-Q2moGVa_183oR8IEDj9che6IZEBwPD9M1ML-XsyAJ7OiDz9vOKMa3bpIQWB9hsqD2m0cpPJfDuHQ9Q7RQGwFZtbq_mZF9hoM2ROVlwym2PD0qBr2IAEqCXVzLXdlc3QtMjCiBg.m3u8 -bsf:a aac_adtstoasc -c copy -f flv rtmp://rtmp.livepeer.com/live/ef15-6p9j-vmm0-w55w"
