
# File: .github/workflows/workflowForFile.yml

on:
  workflow_dispatch:
    inputs:
      m3u8_url:
        description: ''
        required: true
        type: string
      livestream_token:
        description: ''
        required: true
        type: string
      app_id:
        description: ''
        required: true
        type: string
      app_secret:
        description: ''
        required: true
        type: string
      tenant_id:
        description: ''
        required: true
        type: string


name: AzureCLISampleForFile

jobs:

  build-and-deploy:
    runs-on: self-hosted
    steps:

    - name: Run Azure CLi
      run : | 
          ./script/start_ffmpeg.ps1
  
