
# File: .github/workflows/workflowForFile.yml

on:
  workflow_dispatch:
    inputs:
      m3u8_url:
        description: ''
        required: true
        type: string
      livestream_token:
        description: ''
        required: true
        type: string

name: AzureCLISampleForFile

jobs:

  build-and-deploy:
    runs-on: github-custom-runner
    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Checkout
      uses: actions/checkout@v1

    - name: Azure CLI script file
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az container exec --resource-group rg-livestream-dev --name ffmpeglivestream --exec-command "ffmpeg -fflags +igndts -hide_banner -i https://video-weaver.jfk04.hls.ttvnw.net/v1/playlist/CqIEIXOg-APosCEA_lO6DGp7WxKiCjtHS-LcLcJBPYe0R50F5E33zsjYk8XhsKjtQBgCeCrdx_OP20aBjYfXroXUMfzSBI-xNGVS8X0mPdo64p4AC8n47a-790HWEeiJKiMyW7Z2F_uizJy940B3T2gm6lyIcc927a58aEkdUhTO0qFbULQetJrcnIaxUHcwYIoSI5PVQK8pBA9L_odKu9lpSdjxQU_q9jANIUpUTP2mb-QVb7R93xyiPwNFWhok3kRRrFXcjk8q2uHnooXZnBLIjWLQqXg5g7Ipl-TbqagKVJGmers5f20urfycFynCkSv91ZOiz9vhsQ50LzH2Yir4Isefxn3yMzhlNFgHEd1htxPKxKjJU-Pyymb_RwbQ6JGnTugaUlcECU_5OoUFBCjvwFUhj-7kXKVFid2g3BNwLvRsP8oeTRNiTtPFaSg43jULu3URPnH1oq13jlT4wy4mPZFtRlSfyNbnOIMCgrWuvmphl1PWfpxpzTCC-QPuSxmSzKCw2OOtJ4I7k5wb41pOQb0PeWuOU-VqXACSmpJnIUdu-vjxfroOYoB1NwAH-vnaQS2aOcVnuFy8LgqMM5dMH5FxLq9VPPtwrIgoYN_9LEorDPu2fwbwK3_HWsrOSeL3oLIgo4qeP-gFzFY7XMeylrVtZUJuNOztvlOnuvzFuDyvedGI0GKBw7F1vI7xdxco8IC9ZDLdUOVMOATxYb3pPEsqGgyDHv93ZsJa_waEmpAgASoJdXMtZWFzdC0yMKAG.m3u8 -bsf:a aac_adtstoasc -c copy -f flv rtmp://rtmp.livepeer.com/live/ef15-6p9j-vmm0-w55w" --debug
