
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
   steps: 
    - name: Azure App Configuration Sync
      uses: Azure/AppConfiguration-Sync@v1.1.3
      with:
          configurationFile: 'appsettings.json'
          format: 'json'
          # Replace <ConnectionString> with the name of the secret in your repository
          LivePeerConfig__: "@Microsoft.KeyVault(SecretUri=https://decentraldemo-kv.vault.azure.net/secrets/liverpeerKey/)"
          separator: ':'
